# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('spotify_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name=b'Spotify user ID')),
                ('spotify_access_token', models.CharField(max_length=128, verbose_name=b'Spotify Web API Access Token')),
                ('spotify_access_expiry', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Spotify Access Token Expiry Date')),
                ('spotify_refresh_token', models.CharField(max_length=128, verbose_name=b'Spotify Web API Refresh Token')),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name=b'Room Name')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Creation Date')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crowd_control.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64, verbose_name=b'Spotify track ID')),
                ('artist_name', models.CharField(max_length=64, verbose_name=b'Artist Name')),
                ('track_name', models.CharField(max_length=64, verbose_name=b'Track Name')),
                ('album_name', models.CharField(max_length=64, verbose_name=b'Album Name')),
                ('track_length_ms', models.IntegerField(verbose_name=b'Track Length (ms)')),
                ('vote_count', models.IntegerField(default=0, verbose_name=b'Vote Count')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Date Added')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='crowd_control.Room')),
            ],
            options={
                'ordering': ['-vote_count', 'date_added'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('spotify_id', 'room')]),
        ),
    ]
