# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64, verbose_name=b'Spotify user ID')),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Creation Date')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd_control.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64, verbose_name=b'Spotify track ID')),
                ('artist_name', models.CharField(max_length=64, verbose_name=b'Artist Name')),
                ('track_name', models.CharField(max_length=64, verbose_name=b'Track Name')),
                ('album_name', models.CharField(max_length=64, verbose_name=b'Album Name')),
                ('track_length_ms', models.IntegerField(verbose_name=b'Track Length (ms)')),
                ('vote_count', models.IntegerField(default=0, verbose_name=b'Vote Count')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd_control.Room')),
            ],
        ),
    ]
