# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crowd_control.Host'),
        ),
    ]
